[package]
name = "quantum_pgp"
version = "0.1.0"
edition = "2021"

[dependencies]
oqs = "0.7.2"
aes-gcm = "0.10"
rand_core = "0.6"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
hkdf = "0.12"
sha2 = "0.10"
argon2 = "0.4"
hmac = "0.12"
rand = "0.8"
cfg-if = "1.0"